# Site settings
author: Jesse Summer-Lavigne
title: My Coding Thoughts
header-img: img/home-bg.png
email: jessesl22@gmail.com
copyright_name: Jesse Summer-Lavigne
description: > # this means to ignore newlines until "baseurl:"
  A Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Yahsei

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
